<?php

/**
 * BasePPE_Game_Game
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $game
 * @property Doctrine_Collection $PPE_Game_Games
 * 
 * @method string              getGame()           Returns the current record's "game" value
 * @method Doctrine_Collection getPPEGameGames()   Returns the current record's "PPE_Game_Games" collection
 * @method PPE_Game_Game       setGame()           Sets the current record's "game" value
 * @method PPE_Game_Game       setPPEGameGames()   Sets the current record's "PPE_Game_Games" collection
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_Game_Game extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__game__game');
        $this->hasColumn('game', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             'notnull' => true,
             ));


        $this->index('game_index', array(
             'fields' => 
             array(
              0 => 'game',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PPE_Song_Game as PPE_Game_Games', array(
             'local' => 'id',
             'foreign' => 'game_id'));
    }
}