<?php

/**
 * BasePPE_User_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $role
 * @property integer $value
 * @property Doctrine_Collection $PPE_User_Users
 * 
 * @method string              getRole()           Returns the current record's "role" value
 * @method integer             getValue()          Returns the current record's "value" value
 * @method Doctrine_Collection getPPEUserUsers()   Returns the current record's "PPE_User_Users" collection
 * @method PPE_User_Role       setRole()           Sets the current record's "role" value
 * @method PPE_User_Role       setValue()          Sets the current record's "value" value
 * @method PPE_User_Role       setPPEUserUsers()   Sets the current record's "PPE_User_Users" collection
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_User_Role extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__user__role');
        $this->hasColumn('role', 'string', 32, array(
             'type' => 'string',
             'notnull' => 'true; unique: true',
             'length' => '32',
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));

        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PPE_User_User as PPE_User_Users', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}