<?php

/**
 * BasePPE_Vote_Vote
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property timestamp $created
 * @property timestamp $updated
 * @property integer $user_id
 * @property integer $edit_id
 * @property integer $rating
 * @property string $reason
 * @property boolean $is_problem
 * @property PPE_User_User $PPE_User_User
 * @property PPE_Edit_Edit $PPE_Edit_Edit
 * 
 * @method timestamp     getCreated()       Returns the current record's "created" value
 * @method timestamp     getUpdated()       Returns the current record's "updated" value
 * @method integer       getUserId()        Returns the current record's "user_id" value
 * @method integer       getEditId()        Returns the current record's "edit_id" value
 * @method integer       getRating()        Returns the current record's "rating" value
 * @method string        getReason()        Returns the current record's "reason" value
 * @method boolean       getIsProblem()     Returns the current record's "is_problem" value
 * @method PPE_User_User getPPEUserUser()   Returns the current record's "PPE_User_User" value
 * @method PPE_Edit_Edit getPPEEditEdit()   Returns the current record's "PPE_Edit_Edit" value
 * @method PPE_Vote_Vote setCreated()       Sets the current record's "created" value
 * @method PPE_Vote_Vote setUpdated()       Sets the current record's "updated" value
 * @method PPE_Vote_Vote setUserId()        Sets the current record's "user_id" value
 * @method PPE_Vote_Vote setEditId()        Sets the current record's "edit_id" value
 * @method PPE_Vote_Vote setRating()        Sets the current record's "rating" value
 * @method PPE_Vote_Vote setReason()        Sets the current record's "reason" value
 * @method PPE_Vote_Vote setIsProblem()     Sets the current record's "is_problem" value
 * @method PPE_Vote_Vote setPPEUserUser()   Sets the current record's "PPE_User_User" value
 * @method PPE_Vote_Vote setPPEEditEdit()   Sets the current record's "PPE_Edit_Edit" value
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_Vote_Vote extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__vote__vote');
        $this->hasColumn('created', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('updated', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('edit_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('rating', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('reason', 'string', null, array(
             'type' => 'string',
             'notnull' => false,
             ));
        $this->hasColumn('is_problem', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => 0,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PPE_User_User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('PPE_Edit_Edit', array(
             'local' => 'edit_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}