<?php

/**
 * BaseITG_User_Condiment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property char $oregano
 * @property char $salt
 * @property char $pepper
 * @property ITG_User_User $ITG_User_User
 * 
 * @method integer            getUserId()        Returns the current record's "user_id" value
 * @method char               getOregano()       Returns the current record's "oregano" value
 * @method char               getSalt()          Returns the current record's "salt" value
 * @method char               getPepper()        Returns the current record's "pepper" value
 * @method ITG_User_User      getITGUserUser()   Returns the current record's "ITG_User_User" value
 * @method ITG_User_Condiment setUserId()        Sets the current record's "user_id" value
 * @method ITG_User_Condiment setOregano()       Sets the current record's "oregano" value
 * @method ITG_User_Condiment setSalt()          Sets the current record's "salt" value
 * @method ITG_User_Condiment setPepper()        Sets the current record's "pepper" value
 * @method ITG_User_Condiment setITGUserUser()   Sets the current record's "ITG_User_User" value
 * 
 * @package    itgedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseITG_User_Condiment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i_t_g__user__condiment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('oregano', 'char', 32, array(
             'type' => 'char',
             'length' => 32,
             'notnull' => true,
             ));
        $this->hasColumn('salt', 'char', 5, array(
             'type' => 'char',
             'length' => 5,
             'notnull' => true,
             ));
        $this->hasColumn('pepper', 'char', 64, array(
             'type' => 'char',
             'length' => 64,
             'notnull' => true,
             ));


        $this->index('spice_index', array(
             'fields' => 
             array(
              0 => 'user_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');

        $this->check('length(oregano) = 32');
        $this->check('length(salt) = 5');
        $this->check('length(pepper) = 64');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ITG_User_User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignKeyName' => 'condiment_user_fk'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}