<?php

/**
 * BasePPE_User_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $role
 * @property Doctrine_Collection $PPE_User_Powers
 * 
 * @method string              getRole()            Returns the current record's "role" value
 * @method Doctrine_Collection getPPEUserPowers()   Returns the current record's "PPE_User_Powers" collection
 * @method PPE_User_Role       setRole()            Sets the current record's "role" value
 * @method PPE_User_Role       setPPEUserPowers()   Sets the current record's "PPE_User_Powers" collection
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_User_Role extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__user__role');
        $this->hasColumn('role', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             'notnull' => true,
             'unique' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('PPE_User_Power as PPE_User_Powers', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}