<?php

/**
 * BasePPE_Song_Stop
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $song_id
 * @property decimal $beat
 * @property decimal $break
 * @property PPE_Song_Song $PPE_Song_Song
 * 
 * @method integer       getSongId()        Returns the current record's "song_id" value
 * @method decimal       getBeat()          Returns the current record's "beat" value
 * @method decimal       getBreak()         Returns the current record's "break" value
 * @method PPE_Song_Song getPPESongSong()   Returns the current record's "PPE_Song_Song" value
 * @method PPE_Song_Stop setSongId()        Sets the current record's "song_id" value
 * @method PPE_Song_Stop setBeat()          Sets the current record's "beat" value
 * @method PPE_Song_Stop setBreak()         Sets the current record's "break" value
 * @method PPE_Song_Stop setPPESongSong()   Sets the current record's "PPE_Song_Song" value
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_Song_Stop extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__song__stop');
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('beat', 'decimal', 8, array(
             'type' => 'decimal',
             'notnull' => true,
             'default' => 0,
             'size' => 8,
             'scale' => 4,
             'length' => 8,
             ));
        $this->hasColumn('break', 'decimal', 4, array(
             'type' => 'decimal',
             'notnull' => false,
             'size' => 4,
             'scale' => 2,
             'length' => 4,
             ));


        $this->index('stop_index', array(
             'fields' => 
             array(
              0 => 'song_id',
              1 => 'beat',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');

        $this->check('beat > 0');
        $this->check('break IS NULL OR break > 0');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PPE_Song_Song', array(
             'local' => 'song_id',
             'foreign' => 'id',
             'foreignKeyName' => 'stop_song_fk'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}