<?php

/**
 * BasePPE_Song_Game
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $song_id
 * @property integer $game_id
 * @property PPE_Song_Song $PPE_Song_Song
 * @property PPE_Game_Game $PPE_Game_Game
 * 
 * @method integer       getSongId()        Returns the current record's "song_id" value
 * @method integer       getGameId()        Returns the current record's "game_id" value
 * @method PPE_Song_Song getPPESongSong()   Returns the current record's "PPE_Song_Song" value
 * @method PPE_Game_Game getPPEGameGame()   Returns the current record's "PPE_Game_Game" value
 * @method PPE_Song_Game setSongId()        Sets the current record's "song_id" value
 * @method PPE_Song_Game setGameId()        Sets the current record's "game_id" value
 * @method PPE_Song_Game setPPESongSong()   Sets the current record's "PPE_Song_Song" value
 * @method PPE_Song_Game setPPEGameGame()   Sets the current record's "PPE_Game_Game" value
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_Song_Game extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__song__game');
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             ));


        $this->index('songs_in_game_index', array(
             'fields' => 
             array(
              0 => 'song_id',
              1 => 'game_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PPE_Song_Song', array(
             'local' => 'song_id',
             'foreign' => 'id',
             'foreignKeyName' => 'game_song_fk'));

        $this->hasOne('PPE_Game_Game', array(
             'local' => 'game_id',
             'foreign' => 'id',
             'foreignKeyName' => 'game_game_fk'));
    }
}