<?php

/**
 * BasePPE_Song_BPM
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $song_id
 * @property float $beat
 * @property float $bpm
 * @property PPE_Song_Song $PPE_Song_Song
 * 
 * @method integer       getSongId()        Returns the current record's "song_id" value
 * @method float         getBeat()          Returns the current record's "beat" value
 * @method float         getBpm()           Returns the current record's "bpm" value
 * @method PPE_Song_Song getPPESongSong()   Returns the current record's "PPE_Song_Song" value
 * @method PPE_Song_BPM  setSongId()        Sets the current record's "song_id" value
 * @method PPE_Song_BPM  setBeat()          Sets the current record's "beat" value
 * @method PPE_Song_BPM  setBpm()           Sets the current record's "bpm" value
 * @method PPE_Song_BPM  setPPESongSong()   Sets the current record's "PPE_Song_Song" value
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_Song_BPM extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__song__b_p_m');
        $this->hasColumn('song_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('beat', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             'default' => 0,
             ));
        $this->hasColumn('bpm', 'float', null, array(
             'type' => 'float',
             'notnull' => false,
             ));


        $this->index('bpm_index', array(
             'fields' => 
             array(
              0 => 'song_id',
              1 => 'beat',
             ),
             'type' => 'unique',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PPE_Song_Song', array(
             'local' => 'song_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}