<?php

/**
 * BaseITG_User_Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $role
 * @property Doctrine_Collection $ITG_User_Powers
 * 
 * @method string              getRole()            Returns the current record's "role" value
 * @method Doctrine_Collection getITGUserPowers()   Returns the current record's "ITG_User_Powers" collection
 * @method ITG_User_Role       setRole()            Sets the current record's "role" value
 * @method ITG_User_Role       setITGUserPowers()   Sets the current record's "ITG_User_Powers" collection
 * 
 * @package    itgedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseITG_User_Role extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i_t_g__user__role');
        $this->hasColumn('role', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             'notnull' => true,
             'unique' => true,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ITG_User_Power as ITG_User_Powers', array(
             'local' => 'id',
             'foreign' => 'role_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}