<?php

/**
 * BaseITG_User_Power
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $role_id
 * @property ITG_User_User $ITG_User_User
 * @property ITG_User_Role $ITG_User_Role
 * 
 * @method integer        getUserId()        Returns the current record's "user_id" value
 * @method integer        getRoleId()        Returns the current record's "role_id" value
 * @method ITG_User_User  getITGUserUser()   Returns the current record's "ITG_User_User" value
 * @method ITG_User_Role  getITGUserRole()   Returns the current record's "ITG_User_Role" value
 * @method ITG_User_Power setUserId()        Sets the current record's "user_id" value
 * @method ITG_User_Power setRoleId()        Sets the current record's "role_id" value
 * @method ITG_User_Power setITGUserUser()   Sets the current record's "ITG_User_User" value
 * @method ITG_User_Power setITGUserRole()   Sets the current record's "ITG_User_Role" value
 * 
 * @package    itgedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseITG_User_Power extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('i_t_g__user__power');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('role_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 3,
             ));


        $this->index('user_roles_index', array(
             'fields' => 
             array(
              0 => 'user_id',
              1 => 'role_id',
             ),
             'type' => 'unique',
             ));
        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_unicode_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ITG_User_User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'foreignKeyName' => 'power_user_fk'));

        $this->hasOne('ITG_User_Role', array(
             'local' => 'role_id',
             'foreign' => 'id',
             'foreignKeyName' => 'power_role_fk'));
    }
}