<?php

/**
 * BasePPE_User_Condiment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property string $oregano
 * @property string $salt
 * @property string $pepper
 * @property PPE_User_User $PPE_User_User
 * 
 * @method integer            getUserId()        Returns the current record's "user_id" value
 * @method string             getOregano()       Returns the current record's "oregano" value
 * @method string             getSalt()          Returns the current record's "salt" value
 * @method string             getPepper()        Returns the current record's "pepper" value
 * @method PPE_User_User      getPPEUserUser()   Returns the current record's "PPE_User_User" value
 * @method PPE_User_Condiment setUserId()        Sets the current record's "user_id" value
 * @method PPE_User_Condiment setOregano()       Sets the current record's "oregano" value
 * @method PPE_User_Condiment setSalt()          Sets the current record's "salt" value
 * @method PPE_User_Condiment setPepper()        Sets the current record's "pepper" value
 * @method PPE_User_Condiment setPPEUserUser()   Sets the current record's "PPE_User_User" value
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePPE_User_Condiment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('p_p_e__user__condiment');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('oregano', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '32',
             ));
        $this->hasColumn('salt', 'string', 5, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '5',
             ));
        $this->hasColumn('pepper', 'string', 64, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '64',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('PPE_User_User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}