<?php

/**
 * ITG_User_User
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    itgedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ITG_User_User extends BaseITG_User_User
{
}
