<?php

/**
 * ITG_Song_BPM
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    itgedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ITG_Song_BPM extends BaseITG_Song_BPM
{
}
