<?php

/**
 * PPE_Song_Game
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    pumpproedits
 * @subpackage model
 * @author     JasonWolfman2000Felds
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class PPE_Song_Game extends BasePPE_Song_Game
{
}
