# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  base_edits_per_page: 30
  max_edit_file_size: 30720
  max_edit_name_length: 12
  max_difficulty_rating: 99
  min_difficulty_rating: 1
  max_username_length: 12
  min_username_length: 4
  min_password_length: 5
  max_email_length: 320
  min_salt_char: 48
  max_salt_char: 126
  min_oregano_length: 32
  max_oregano_length: 32
  max_subject_length: 50
  min_email_length: 20
  chart_header_height: 96
  chart_footer_height: 32
  chart_arrow_height: 16
  chart_arrow_width: 16
  chart_single_cols: 5
  chart_double_cols: 10
  chart_column_sep: 32
  chart_measures_col: 6
  chart_beat_height: 16
  chart_speed_mod: 2
  chart_beat_p_measure: 4
  chart_def_file: '/svg/arrowdef.svg'
