# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/09-Cache

default:
  enabled:     false
  with_layout: false
  lifetime:    86400

_nav_norm:
  enabled:     true
  with_layout: false
  lifetime:    1209600

_nav_chrt:
  enabled:     true
  with_layout: false
  lifetime:    1209600

_memb_in:
  enabled:     true
  with_layout: false
  lifetime:    1209600

_memb_out:
  enabled:     true
  with_layout: false
  lifetime:    1209600

_mess_in:
  enabled:     true
  with_layout: false
  lifetime:    1209600

_mess_out:
  enabled:     true
  with_layout: false
  lifetime:    1209600
