# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: ppehome, action: index }

# temp xml page
xmltest:
  url: /xmltest
  param:
    module: xmltest
    action: index

# credits / thanks page
thanks:
  url: /thanks
  param:
    module: thanks
    action: index

# Base edit page:
base_edit:
  url: /base/:page
  param:
    module: base
    action: index
    page: 1
  requirements:
    page: \d+

# Download a base edit.
download_base_edit:
  url: /base/download/:id/:type
  param:
    module: base
    action: download

# Illegal base download:
download_base_edit_404:
  url: /base/download/*
  param:
    module: base
    action: download

# The dynamic chart generator
chart_gen_get:
  url: /chart
  class: sfRequestRoute
  param:
    module: chart
    action: index
  requirements:
    sf_method: [GET]

# The result of the chart generator.
chart_gen_post:
  url: /chart
  class: sfRequestRoute
  param:
    module: chart
    action: validate
  requirements:
    sf_method: [POST]

# Quickly generate a chart.
chart_quick:
  url: /chart/quick/:id/:kind
  param:
    module: chart
    action: quick
  requirements:
    id: \d+

# The edit stat getter/validator
edit_stat_get:
  url: /stats
  class: sfRequestRoute
  param:
    module: stats
    action: index
  requirements:
    sf_method: [GET]

# The results of the edit stat getter (post)
edit_stat_post:
  url: /stats
  class: sfRequestRoute
  param:
    module: stats
    action: validate
  requirements:
    sf_method: [POST]

# Login page
login_get:
  url: /login
  class: sfRequestRoute
  param:
    module: login
    action: index
  requirements:
    sf_method: [GET]

# Login after submitting
login_post:
  url: /login
  class: sfRequestRoute
  param:
    module: login
    action: validate
  requirements:
    sf_method: [POST]

# Log the user out.
logout:
  url: /logout
  param:
    module: logout
    action: index

# Contact page: fill out the form
contact_get:
  url: /contact
  class: sfRequestRoute
  param:
    module: contact
    action: index
  requirements:
    sf_method: [GET]

# Send the contact email.
contact_post:
  url: /contact
  class: sfRequestRoute
  param:
    module: contact
    action: validate
  requirements:
    sf_method: [POST]

# Confirm someone's account
confirm_get_code:
  url: /confirm/:code
  class: sfRequestRoute
  param:
    module: confirm
    action: index
  requirements:
    sf_method: [GET]

confirm_get:
  # Can I get the URL to work with optional parameters?
  url: /confirm
  class: sfRequestRoute
  param:
    module: confirm
    action: index
  requirements:
    sf_method: [GET]

# Process confirmation request
confirm_post:
  url: /confirm
  class: sfRequestRoute
  param:
    module: confirm
    action: validate
  requirements:
    sf_method: [POST]

# Help getting your account to work
help:
  url: /help
  param:
    module: help
    action: index

# General edits page (this may change)
edits:
  url: /edits
  param:
    module: edits
    action: index

# Edits by song:
edit_song:
  url: /songs
  param:
    module: edits
    action: song

# The chosen song (unsure if I'll use the pager)
edit_csong:
  url: /songs/:id/:page
  param:
    module: edits
    action: chosenSong
    page: 1
  requirements:
    id: \d+

# Edits by user
edit_user:
  url: /users
  param:
    module: edits
    action: user

# Edits made by Andamiro / Official Charts.
edit_official:
  url: /andamiro/:page
  param:
    module: edits
    action: official
    page: 1
  requirements:
    page: \d+

# The chosen user (unsure if I'll use the pager)
edit_cuser:
  url: /users/:id/:page
  param:
    module: edits
    action: chosenUser
    page: 1
  requirements:
    id: \d+

# Download the chosen edit
edit_download:
  url: /edits/download/:id
  param:
    module: edits
    action: download
  requirements:
    id: \d+

# Illegal edit download
edit_download_404:
  url: /edits/download/*
  param:
    module: edits
    action: download

# Registration page
register_get:
  url: /register
  class: sfRequestRoute
  param:
    module: register
    action: index
  requirements:
    sf_method: [GET]

# Once you register:
register_post:
  url: /register
  class: sfRequestRoute
  param:
    module: register
    action: validate
  requirements:
    sf_method: [POST]
