# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: ppehome, action: index }

# credits / thanks page
thanks:
  url: /thanks
  param:
    module: thanks
    action: index

# Base edit page:
base_edit:
  url: /base/:page
  param:
    module: base
    action: index
    page: 1
  requirements:
    page: \d+

# Download a base edit.
download_base_edit:
  url: /base/download/:id/:type
  param:
    module: base
    action: download
  requirements:
    id: \d+

# The edit stat getter/validator
edit_stat_get:
  url: /stats
  class: sfRequestRoute
  param:
    module: stats
    action: index
  requirements:
    sf_method: [GET]

# The results of the edit stat getter (post)
edit_stat_post:
  url: /stats
  class: sfRequestRoute
  param:
    module: stats
    action: validate
  requirements:
    sf_method: [POST]

# Login page
login_get:
  url: /login
  class: sfRequestRoute
  param:
    module: login
    action: index
  requirements:
    sf_method: [GET]

# Login after submitting
login_post:
  url: /login
  class: sfRequestRoute
  param:
    module: login
    action: validate
  requirements:
    sf_method: [POST]

# Log the user out.
logout:
  url: /logout
  param:
    module: logout
    action: index

# Registration page
register_get:
  url: /register
  class: sfRequestRoute
  param:
    module: register
    action: index
  requirements:
    sf_method: [GET]

# Once you register:
register_post:
  url: /register
  class: sfRequestRoute
  param:
    module: register
    action: validate
  requirements:
    sf_method: [POST]

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
