# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:        ITG Edits
    description:  This website allows users to play almost every edit made for the In The Groove series.
    keywords:     ITG, ITG2, Groove, Groove 2, In The Groove 2, In The Groove, edits, Wolfman2000, Jason Felds
    language:     en
    robots:       index, follow

  stylesheets:    []
  javascripts:    []

  has_layout:     true
  layout:         layout
