# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: "text/html; charset=UTF-8"

  metas:
    title:        Pump Pro Edits
    description:  This website allows users to create and share custom made step edits for the arcade game Pump It Up Pro.
    keywords:     Pump It Up Pro, Pump Pro, Pump It Up, Pro, edits, Wolfman2000, Jason Felds
    language:     en
    robots:       index, follow

  stylesheets:    [main.css]

  javascripts:    []

  has_layout:     true
  layout:         layout
