index:
  enabled:     true
  with_layout: false
  lifetime:    1209600

loadSite:
  enabled:     true
  with_layout: false
  lifetime:    1209600

loadSiteEdit:
  enabled:     true
  with_layout: false
  lifetime:    1209600

ajax:
  enabled:     true
  with_layout: false
  lifetime:    1209600

routine:
  enabled:     true
  with_layout: false
  lifetime:    1209600
